### ISSUE TITLE
Permission to use in an ironman compatible Coat of Arms mod?

### ISSUE THREAD

**Issue by smasongarrison** [ArkoG/ARKOpack#1]
Hi, I am working on creating an ironman compatible Coat of Arms mod. I have one that I use for myself that already incorporates a load of mods. But, I am looking to made one that I can share with others.

Do I have permission to incorporate your files into my mod, if I give you credit?

**Comment by ArkoG** [comment]
Hi,
What is your project ?
Are you on Paradox forums ?
What does it imply to have it ironman compatible ?
