### ISSUE TITLE
Mojmirid dynasty CoA seems broken.

### ISSUE THREAD

**Issue by zijistark** [ArkoG/ARKOpack#14]
This is from the Furry Beta. I don't actually know if it's broken, although it does seem out of sorts. Is this WAD?

![image](https://user-images.githubusercontent.com/6268890/52185553-6eaf2480-27d5-11e9-914e-95772a480487.png)

Version.txt:

````
[HIP Release [DEV: 2019-02-03 01:07]]
EMF: Extended Mechanics & Flavor (v9.0-BETA - 2019-02-02)
ARKO Interface (2018-06-16)
SWMH (v3.2-BETA - 2019-02-01)
ARKO Armoiries (2018-06-16)
LTM (C - 2017-12-09)
CPRplus (v3.0.1 - 2019-01-02)
````

**Comment by ArkoG** [comment]
it looks WAD from what the CoA-3 provides 
https://forum.paradoxplaza.com/forum/index.php?threads/historical-dynasty-coa-list-with-culture-and-dates.1144348/
