### ISSUE TITLE
Missing localisation for new customizer CoAs.

### ISSUE THREAD

**Issue by zijistark** [ArkoG/ARKOpack#16]
Kauna said:
> I think the new Zoroastrian CoA are missing some localisation
![image](https://user-images.githubusercontent.com/6268890/52362821-418d8c80-29f6-11e9-9e05-7e62478e1698.png)

Then also said:
> Taoist too
![image](https://user-images.githubusercontent.com/6268890/52362845-5407c600-29f6-11e9-9bd4-7d05fd3ead2d.png)

**Comment by ArkoG** [comment]
fixed
