### ISSUE TITLE
Border Rendering no working properly for certain muslim nation

### ISSUE THREAD

**Issue by Varatnar** [ArkoG/ARKOpack#17]
Muslim group CoA conflicts with basic mechanic to determine border colors of independent nations.

Notes from discord channel :

1. The issue is caused by arko armoirie (coa)
1. The reason it is so is that border colors are determined by the independant primary holding coa color scheme.
1. As far as i could tell, the no rendering border issue only occur with muslim (or similarly working religion). The main holding CoA is not the .tga file associated with the title.

I am opening this issue in hope of clarifying this point in more details.

**Comment by Varatnar** [comment]
Does it happen in random worlds too ? 
 - Yes, it seems unrelated to the state of the game, and only related to CoA or Flags. As such going from muslim to christian and reloading the save will (always so far) fix the border issue of faulty one.

**Comment by Varatnar** [comment]
While I am unsure exactly what causes the issue I shall refer to the Character I have been using to test.

He is `Amir Mujahid of the al-'Amiri Imara` , east coast of hispania on the 1018 start.

Current version of HIP :
[HIP Release 2019-02-06 (Furry1 Beta5)]
EMF: Extended Mechanics & Flavor (v9.0-BETA - 2019-02-05)
Arumba and Internal Tab Shortcuts (2019-01-15)
ARKO Interface (2019-02-06)
SWMH (v3.2-BETA - 2019-02-01)
ARKO Armoiries (2019-02-06)
LTM (C - 2012-02-03)

**Comment by ArkoG** [comment]
since it auto fixes by itself by reload or relaunching i suspect it is not something we have the hand on. I'll try to reproduce and investigate

**Comment by Varatnar** [comment]
The title in question (causing potential issue) is d_valencia.
muslim flag : https://puu.sh/CIHED/dc6de77904.png

**Comment by ArkoG** [comment]
do you encounter the problem with vanilla+arkopack ?

**Comment by Varatnar** [comment]
The problem does not seem to be produced on vanilla. 

I have been viewing the HIP installation as one big block.

Since that is not the case i did some more test and the bug happens with arko armoirie + swmh. The same behavior as described earlier is seen (exactly the same issues).

[HIP Release 2019-02-06 (Furry1 Beta5)]
SWMH (v3.2-BETA - 2019-02-01)
ARKO Armoiries (2019-02-06)

**Comment by ArkoG** [comment]
I guess I found something, it may occur in vanilla. do you have the fourth Coat of arms DLC by chance ?

**Comment by ese-khan** [comment]
I also recall seeing this issue (I'm assuming external borders?) in base SWMH, actually, near Palmyra. Will see if I can reproduce this issue with just SWMH on. This might not be an ARKOArmoiries issue.

**Comment by Varatnar** [comment]
@ArkoG 
I am unsure exactly which that is but here is the list of sheild packs activated
https://puu.sh/CIJ6L/e44c95cd57.png

**Comment by Varatnar** [comment]
Image overview, start date 1018 south hispania.

Expected (SWMH only):
![image](https://user-images.githubusercontent.com/16279559/52436428-462f6f00-2ae2-11e9-8b60-3aa6abd10f14.png)
Actual (SWMH+arko armoirie):
![image](https://user-images.githubusercontent.com/16279559/52436451-4b8cb980-2ae2-11e9-8114-e1e5102d9adf.png)

**Comment by ArkoG** [comment]
ok so could you tru to launch a vanilla game, without arkopack, selecting Abbasids or
Umayyads and see if they have borders or not ?

**Comment by Varatnar** [comment]
Full vanilla ?

They do. Everything has border where it should in vanilla.

**Comment by ArkoG** [comment]
yes full vanilla

**Comment by ArkoG** [comment]
even for these 2 specifics ?

**Comment by Varatnar** [comment]
Yes, even for them.

I've checked for the both of them (different time start). Do you have issue on your side even on full vanilla ?

**Comment by ArkoG** [comment]
no, only possible cases for vanilla are those two :/
if it is not happening in vanilla, it won't get an official fix, even if it can occurs in mods

**Comment by Varatnar** [comment]
I was hoping to pinpoint exactly what causes issue. e.g. X pattern of Y color. In hope to remove such pattern from arko.

**Comment by ArkoG** [comment]
my goal is not to strip stuff from the mod if i can ;)

**Comment by Varatnar** [comment]
I guess we should close this for now and store this somewhere in know issue ?

As far as I can tell the problem only occurs with arko Armoirie, but is caused by some vanilla feature in parsing CoA/Flag.

**Comment by ArkoG** [comment]
fixed

**Comment by Varatnar** [comment]
confirmed fixed as of emf beta-6
