### ISSUE TITLE
Montfort CoA

### ISSUE THREAD

**Issue by Ghibelline** [ArkoG/ARKOpack#4]
Hello, I've created a coat of arms for the house of Montfort that ruled Brittany from 1339-1514 using assets in your mod, and I was wondering if you could add it to the mod?

[https://i.imgur.com/DYRA8by.png](url) is the coat of arms in question

**Comment by ArkoG** [comment]
is it the existing Montfort dynasty that is already in the game ? @Ghibelline

**Comment by Ghibelline** [comment]
@ArkoG It would be for the heir of the duke of Brittany in the 1337 starting date, who was the first of the house of Capetian house of Montfort

**Comment by ArkoG** [comment]
so a dynastic ID right ? @Ghibelline

**Comment by ArkoG** [comment]
so a new dynastic ID right ? @Ghibelline

**Comment by Ghibelline** [comment]
It will need one, yeah, since he's part of the house of Dreux in-game, but I messaged the SWMH team asking if they could rectify that. However, I've also worked on a few other houses you might consider adding

The House of Aberffraw, most important Welsh house https://i.imgur.com/IF9bSer.png
House of Dinefwr, cadet house of Aberffraw, rulers of Deheubarth https://i.imgur.com/dI3bVrn.png
House of Mathrafal, cadet house of Dinefwr, rulers of Powys https://i.imgur.com/I7T0gLJ.png

These are just modified coats of arms of their duchies as close to their historical representatives I could find in the Arko files, but I think it'd be a good addition.

**Comment by Ghibelline** [comment]
@ArkoG

**Comment by ArkoG** [comment]
added the Montfort with their CoA
their dynastic ID is 1000036013
you'd need to deal with SWMH guys for the characters implementation.
I won't do the other suggestions yet.

**Comment by ArkoG** [comment]
added the Montfort with their CoA
their dynastic ID is 1000036013
you'd need to deal with SWMH guys for the characters implementation.
I won't do the other suggestions yet.
@Ghibelline
