### ISSUE TITLE
[Question] what's the purpose of "ARKOpack_Interface/history/characters/zz_ARKOpack_startup.txt"

### ISSUE THREAD

**Issue by lilunxm12** [ArkoG/ARKOpack#5]
What's the purpose of "ARKOpack_Interface/history/characters/zz_ARKOpack_startup.txt"?
By adding this character, the Interface part of mod is no longer Ironman compatible. Is there any special reason to put a charcter creation script under the interface part?

**Comment by NicolasGrosjean** [comment]
The character is created to give a flag sooner in the historic.

With this flag some other mods can know that the ARKOpack Interface is enabled and so have a special behavior.

Is this file the only one thing which breaks ironman ?

**Comment by lilunxm12** [comment]
Yes, it's the only thing. It would be nice if you guys put a line in readme telling pp how to maintain ironman compability though.

**Comment by ArkoG** [comment]
@lilunxm12 this is a version which is not released yet, so that is why it is not documented yet.
